services:
  order-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: config-service
    ports:
      - "8888:8888"
    extra_hosts:
      - "host.docker.internal:host-gateway"  # ⬅ for Linux