replicaCount: 1

image:
  repository: 09naveen/config-server
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8888

env:
  - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
    value: https://github.com/naveenkatoch12609/config-repo.git
  - name: GIT_URI
    value: https://github.com/naveenkatoch12609/config-server.git

resources: {}
